Fix service restart530
wso2/puppet-is pull request #21
Opened 2017-08-15 12:47 UTC by vidurananayakkara

2017-08-15 16:08 UTC, imesh commented on hieradata/dev/wso2/wso2is/pattern-1/default.yaml
> +#wso2::file_list_copy_without_refresh:
I think it would be better to rename this variable to something similar to "service_refresh_file_list" and explain its behaviour in a comment.

2017-08-16 01:50 UTC, chamilad commented
Just as a note, while it's a good practice to use issues and auto-resolvers, it would be better to describe the fix done as well, since the issue only contains the problem description.

2017-08-16 01:51 UTC, chamilad commented on README.md
> +'/etc/puppet/environments/production/modules/wso2is/files/configs'
It would be better to add a link to the Wiki page too.

2017-08-16 04:03 UTC, chamilad commented on hieradata/dev/wso2/wso2is/pattern-1/default.yaml
> +#wso2::file_list_copy_without_refresh:
+1 This can be confusing to a user without inside knowledge of why such a variable was needed.

2017-08-16 04:03 UTC, chamilad requested changes
Requires better documentation as per above comments.

2017-08-16 06:28 UTC, chamilad approved these changes
LGTM

2017-08-16 06:45 UTC, imesh requested changes

2017-08-16 06:45 UTC, imesh commented on README.md
> +[Please Enter Primary KeyStore Password of Carbon Server : ]
We might not need to make the first letter of all words uppercase in a sentence. Shall we refine this to following?
"[Please enter the primary keystore password of the Carbon server: ]"

2017-08-16 06:45 UTC, imesh commented on hieradata/dev/wso2/wso2is/pattern-1/default.yaml
> +# Puppet file list to be copied triggering restart
Please refer feedback in https://github.com/wso2/puppet-base/pull/33 for this comment line.

2017-08-16 06:45 UTC, imesh commented on hieradata/dev/wso2/wso2is/pattern-1/default.yaml
> +# Puppet file list to be copied without restarting the service
Please refer feedback in wso2/puppet-base#33 for this comment line.

2017-08-16 06:45 UTC, imesh commented on hieradata/dev/wso2/wso2is/pattern-1/key-manager.yaml
> +# Puppet file list to be copied triggering restart
Please refer feedback in wso2/puppet-base#33 for this comment line.

2017-08-16 06:45 UTC, imesh commented on hieradata/dev/wso2/wso2is/pattern-1/key-manager.yaml
> +# Puppet file list to be copied without restarting the service
Please refer feedback in wso2/puppet-base#33 for this comment line.

2017-08-16 06:45 UTC, imesh commented on hieradata/dev/wso2/wso2is/pattern-2/default.yaml
> +# Puppet file list to be copied triggering restart
Please refer feedback in wso2/puppet-base#33 for this comment line.

2017-08-16 06:45 UTC, imesh commented on hieradata/dev/wso2/wso2is/pattern-2/default.yaml
> +# Puppet file list to be copied without restarting the service
Please refer feedback in wso2/puppet-base#33 for this comment line.

2017-08-16 06:45 UTC, imesh commented on hieradata/dev/wso2/wso2is/pattern-2/key-manager.yaml
> +# Puppet file list to be copied triggering restart
Please refer feedback in wso2/puppet-base#33 for this comment line.

2017-08-16 06:45 UTC, imesh commented on hieradata/dev/wso2/wso2is/pattern-2/key-manager.yaml
> +# Puppet file list to be copied without restarting the service
Please refer feedback in wso2/puppet-base#33 for this comment line.

2017-08-16 06:45 UTC, imesh commented on hieradata/dev/wso2/wso2is/pattern-3/default.yaml
> +# Puppet file list to be copied triggering restart
Please refer feedback in wso2/puppet-base#33 for this comment line.

2017-08-16 06:45 UTC, imesh commented on hieradata/dev/wso2/wso2is/pattern-3/default.yaml
> +# Puppet file list to be copied without restarting the service
Please refer feedback in wso2/puppet-base#33 for this comment line.

2017-08-16 07:26 UTC, vidurananayakkara commented on README.md
> +[Please Enter Primary KeyStore Password of Carbon Server : ]
This is a prompt we get when executing `sh ciphertool.sh -Dconfigure` and is related the carbon secure vault

2017-08-16 07:33 UTC, vidurananayakkara commented on hieradata/dev/wso2/wso2is/pattern-1/default.yaml
> +# Puppet file list to be copied triggering restart
Changed as requested

2017-08-16 08:00 UTC, imesh approved these changes

2017-08-16 08:00 UTC, merged