Add secure vault configuration files to the file list
wso2/puppet-is pull request #9
Opened 2017-07-31 14:33 UTC by vidurananayakkara

Added configured secure vault files (cipher-tool.properties, cipher-text.properties, secret-conf.properties, password-tmp) to the puppet files list to be copied
Resolves #8

2017-07-31 14:57 UTC, chamilad requested changes
SecureVault files should be commented out by default.

2017-08-01 04:40 UTC, vidurananayakkara commented
@chamilad The copying of secure vault files are commented out by default as requested.

2017-08-01 06:26 UTC, imesh approved these changes

2017-08-01 06:30 UTC, chamilad approved these changes

2017-08-01 06:30 UTC, merged